### ISSUE TITLE
Join.py nefunguje

### ISSUE THREAD

**Issue by ghost** [MiftikCZ/MiftikRAID#1]
Zdravím,
Joinování účtů přes join.py nefunguje, v konzoli sice vyjede úspěšný join, ale na serveru se neobjeví.
![miftikraid issue](https://user-images.githubusercontent.com/50925467/134081411-d6500313-16c3-4808-b699-02d0cc9fd1c3.png)

**Comment by raDekaN** [comment]
lmao musis dat jen kod co je .gg/[kod]
